apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-container
        image: 203553384314.dkr.ecr.sa-east-1.amazonaws.com/vini1321-eks-repo.amazonaws.com/vini1321-eks-repo:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: hello-app
  ports:
  - port: 80
    targetPort: 5000
